#include "timertemplateqt.h"
#include <QCoreApplication>

TimerTemplateQt::TimerTemplateQt(int expireTimeMs) :
    m_expireTimeMs(expireTimeMs)
{
}

void TimerTemplateQt::noteWhenCalledFromTest()
{
    static bool checked = false;
    if (checked)
        return;
    checked = true;
    if (QCoreApplication::instance()->applicationName().startsWith("test_"))
        qCritical("TimerFactoryQtForTest::enableTest() called? / timer generated by TimerFactoryQt?");
}
